title: 

data_dir: /data/allen/climate_data
log_dir: logs


batch_size: 1
lr: 0.0001
global_batch_idx: 0
batch_dropout: 0.5
variables: 26

base_lr: 0.0001
max_lr: 0.01
optim: adam
weight_decay: 0.05
decay_steps: 10
decay_rate: 0.9
gamma: 0.9

patience: 20
best_loss: 0
context_percentage_low: 0.2
context_percentage_high: 0.5

model:
  l1_input_dim: 108
  l1_output_dim: 26
  l2_input_dim: 108
  l2_output_dim: 26

  num_heads: 4
  dropout: 0.2
  attention_layers: 3
  hidden_dim: 64
  hidden_layers: 3
  
load_checkpoint: False