title: MFANP

data_dir: /data/kai
log_dir: logs

batch_size: 1
lr: 0.000139
global_batch_idx: 0
batch_dropout: 0.5
variables: 26

optim: adam
weight_decay: 0.06818202991034834
decay_steps: 5
decay_rate: 0.9
gamma: 1

patience: 20
best_loss: 0
context_percentage_low: 0.2
context_percentage_high: 0.5

model:
  l1_input_dim: 108
  l2_input_dim: 108
  l1_output_dim: 26
  l2_output_dim: 26

  num_heads: 16
  dropout_rate: 0.1748127815197366
  attention_layers: 4
  hidden_dim: 160
  hidden_layers: 3
  leaky_relu_slope: 0.15

  z_hidden_layers: 2
  z_hidden_dim: 128
  z_dim: 128
  
load_checkpoint: False