title: baseline_26

data_dir: /data/allen/climate_data
log_dir: logs

batch_size: 1
lr: 0.0005
global_batch_idx: 0
batch_dropout: 0.5
variables: 26

base_lr: 0.0001
max_lr: 0.01
optim: adam
weight_decay: 0.01
decay_steps: 10000
decay_rate: 1
gamma: 1

patience: 250
best_loss: 99999

model:
  l2_input_dim: 108
  l2_output_dim: 26

  num_heads: 8
  dropout: 0.2
  attention_layers: 3
  hidden_dim: 64
  hidden_layers: 3

  context_percentage_low: 0.2
  context_percentage_high: 0.5

load_checkpoint: baseline_26_seed0_lr0.0005_bs_1_Tue Feb 14 10:53:09 2023
