title: SFNP_train

data_dir: /data/kai/
log_dir: logs

batch_size: 1
lr: 0.000227
global_batch_idx: 0

decay_rate: 0.9

max_patience: 50
patience: 50
best_loss: 0

context_percentage_low: 0.2
context_percentage_high: 0.5

model:
  input_dim: 108
  output_dim: 26
  hidden_layers: 7
  hidden_dim: 512
  z_hidden_layers: 4
  z_hidden_dim: 128
  z_dim: 128
  leaky_relu_slope: 0.15
  dropout_rate: 0.01

load_checkpoint: False