title: transfer
data_dir: /data/kai
log_dir: logs

batch_size: 1
lr: 0.000025
global_batch_idx: 0
batch_dropout: 0.1

weight_decay: 0.05
decay_rate: 0.95

max_patience: 50
patience: 0
best_loss: 0

model:
  input_dim: 108
  output_dim: 26
  num_heads: 4
  attention_layers: 7
  n_embd: 256
  dropout: 0.01
  
load_checkpoint: false
transfer_learning: logs/low_seed0_lr2.5e-05_bs_1_Thu May 18 07:56:21 2023/best.pt