title: transformer_train

data_dir: /data/allen/climate_data
log_dir: logs

batch_size: 1
lr: 7.7e-05
global_batch_idx: 0
batch_dropout: 0.1

weight_decay: 0.04227092357481125
decay_steps: 10
decay_rate: 0.9

patience: 20
best_loss: 999999999

model:
  num_heads: 4
  attention_layers: 12
  n_embd: 48
  dropout: 0.0057435876268728155
  input_dim: 108
  output_dim: 26
  
load_checkpoint: false