title: transformer_train

data_dir: /data/kai
log_dir: logs

batch_size: 1
lr: 0.000227
global_batch_idx: 0
batch_dropout: 0.1

weight_decay: 0.04227092357481125
decay_steps: 10
decay_rate: 0.95

patience: 50
best_loss: 0

model:
  input_dim: 108
  output_dim: 26
  num_heads: 4
  attention_layers: 7
  n_embd: 256
  dropout: 0.01
  
load_checkpoint: false