title: NN

data_dir: /data/kai/
log_dir: logs

batch_size: 1
lr: 0.000227
global_batch_idx: 0

decay_rate: 0.9

max_patience: 50
patience: 0
best_loss: 0

model:
  l2_input_dim: 108
  l2_output_dim: 26
  num_layers: 7
  num_nodes: 512
  dropout_rate: 0.01
  leaky_relu_slope: 0.15
  dropout_rate: 0.01


load_checkpoint: false
transfer_learning: false