title: mfnp

data_dir: /data/kai
log_dir: logs
nested: true

batch_size: 1
lr: 0.000227
global_batch_idx: 0
batch_dropout: 0.1

weight_decay: 0
decay_steps: 10000
decay_rate: 0.9

patience: 200
best_loss: 999999999
context_percentage_low: 0.2
context_percentage_high: 0.5

model:
  hidden_layers: 2
  z_hidden_layers: 2
  z_hidden_dim: 128
  z_dim: 512
  l1_input_dim: 108
  l2_input_dim: 108
  l1_output_dim: 26
  l2_output_dim: 26
  hidden_dim: 512

load_checkpoint: false