title: SFANP_train

data_dir: /data/kai
log_dir: logs

batch_size: 1
batch_dropout: 0.5
lr: 0.000227
decay_rate: 0.9

global_batch_idx: 0
max_patience: 50
patience: 0
best_loss: 0

context_percentage_low: 0.2
context_percentage_high: 0.5

model:
  l2_input_dim: 108
  l2_output_dim: 26

  num_heads: 16
  attention_layers: 7
  hidden_dim: 192
  hidden_layers: 3
  leaky_relu_slope: 0.15
  dropout_rate: 0.01

load_checkpoint: false