title: Low

data_dir: /data/kai
log_dir: logs

batch_size: 1
lr: 0.0000139
global_batch_idx: 0
batch_dropout: 0.5
variables: 26

base_lr: 0.0001
max_lr: 0.01
optim: adam
weight_decay: 0.06818202991034834
decay_steps: 5
decay_rate: 0.9
gamma: 1

max_patience: 20
patience: 0
best_loss: 0
context_percentage_low: 0.2
context_percentage_high: 0.5

model:
  l2_input_dim: 108
  l2_output_dim: 26

  num_heads: 16
  dropout_rate: 0.1748127815197366
  attention_layers: 12
  hidden_dim: 160
  hidden_layers: 3
  leaky_relu_slope: 0.15

load_checkpoint: false