title: sf_attn_low

data_dir: /data/allen/climate_data
# /dta/allen/climate_data
log_dir: logs

batch_size: 1
lr: 0.000139
global_batch_idx: 0
batch_dropout: 0.5
variables: 26

base_lr: 0.0001
max_lr: 0.01
optim: adam
weight_decay: 0.06818202991034834
decay_steps: 5
decay_rate: 0.9
gamma: 1

patience: 20
best_loss: 0
context_percentage_low: 0.2
context_percentage_high: 0.5

model:
  l2_input_dim: 108
  l2_output_dim: 26

  num_heads: 16
  dropout: 0.1748127815197366
  attention_layers: 12
  hidden_dim: 160
  hidden_layers: 3

load_checkpoint: false