title: sfattn_train

data_dir: /home/mkim/Nserver/climate_processes/data
log_dir: logs

batch_size: 1
lr: 0.000139
global_batch_idx: 0
batch_dropout: 0.5
variables: 26

base_lr: 0.0001
max_lr: 0.01
optim: adam
weight_decay: 0.06818202991034834
decay_steps: 5
decay_rate: 0.5
gamma: 1

patience: 250
best_loss: 99999

model:
  l2_input_dim: 108
  l2_output_dim: 26

  num_heads: 16
  dropout: 0.1748127815197366
  attention_layers: 12
  hidden_dim: 160
  hidden_layers: 3

  context_percentage_low: 0.2
  context_percentage_high: 0.5

load_checkpoint: 